FROM golang:1.20-alpine3.17 as builder

RUN apk --no-cache add make git

COPY . /src

WORKDIR /src

RUN make build-client


FROM alpine:3.17

COPY --from=builder /src/bin/client /usr/local/bin/client

EXPOSE 7700

CMD ["/usr/local/bin/client", "--debug=false"]
