FROM golang:1.20-alpine3.17 as builder

RUN apk --no-cache add make git

COPY . /src

WORKDIR /src

RUN make build-server


FROM alpine:3.17

COPY --from=builder /src/bin/server /usr/local/bin/server
COPY --from=builder /src/assets/quotes.txt /opt/powow/quotes.txt

EXPOSE 7700

ENTRYPOINT ["/usr/local/bin/server", "--debug=false", "--quotes-file-path=/opt/powow/quotes.txt"]
